# Assignment 11: Review

We will review material covered so far in this course with short questions similar to what you might expect on the Final Exam. 

First review the lecture notes. Then try to do this assignment without referring to ANY external material to simulate exam conditions.

In [152]:
import numpy as np
import pandas as pd
from collections import Counter
from toolz import reduce
import timeit

from sklearn.decomposition import NMF
from string import punctuation
from scipy.spatial.distance import pdist, squareform

In [28]:
%load_ext cython

**1**. (20 points)

- Generate the matrices A and B without copying and pasting.

```
A =   [[8, 7, 6, 5, 4, 3, 2, 1, 0],
       [7, 6, 5, 4, 3, 2, 1, 0, 1],
       [6, 5, 4, 3, 2, 1, 0, 1, 2],
       [5, 4, 3, 2, 1, 0, 1, 2, 3],
       [4, 3, 2, 1, 0, 1, 2, 3, 4],
       [3, 2, 1, 0, 1, 2, 3, 4, 5],
       [2, 1, 0, 1, 2, 3, 4, 5, 6],
       [1, 0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]]
```

and 

```
B =   [[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 0, 1, 2, 3, 4, 5, 6, 7],
       [2, 1, 0, 1, 2, 3, 4, 5, 6],
       [3, 2, 1, 0, 1, 2, 3, 4, 5],
       [4, 3, 2, 1, 0, 1, 2, 3, 4],
       [5, 4, 3, 2, 1, 0, 1, 2, 3],
       [6, 5, 4, 3, 2, 1, 0, 1, 2],
       [7, 6, 5, 4, 3, 2, 1, 0, 1],
       [8, 7, 6, 5, 4, 3, 2, 1, 0]]
```

- Is matrix multiplication of A and B commutative?
- What is the Frobenius distance between A and B?
- Find the best rank 2 approximation of A in terms of Frobenius distance.

# Q1.1
**Generate the matrices A and B without copying and pasting.**

In [17]:
A = np.fromfunction(lambda i, j: abs((i-4) + (j-4)), (9, 9), dtype = int)
print(A)

[[8 7 6 5 4 3 2 1 0]
 [7 6 5 4 3 2 1 0 1]
 [6 5 4 3 2 1 0 1 2]
 [5 4 3 2 1 0 1 2 3]
 [4 3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4 5]
 [2 1 0 1 2 3 4 5 6]
 [1 0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7 8]]


In [18]:
B = np.fromfunction(lambda i, j: abs(i - j), (9, 9), dtype = int)
print(B)

[[0 1 2 3 4 5 6 7 8]
 [1 0 1 2 3 4 5 6 7]
 [2 1 0 1 2 3 4 5 6]
 [3 2 1 0 1 2 3 4 5]
 [4 3 2 1 0 1 2 3 4]
 [5 4 3 2 1 0 1 2 3]
 [6 5 4 3 2 1 0 1 2]
 [7 6 5 4 3 2 1 0 1]
 [8 7 6 5 4 3 2 1 0]]


# Q1.2
**Is matrix multiplication of A and B commutative?**

yes

In [21]:
np.allclose(A @ B, B @ A)

True

# Q1.3
**What is the Frobenius distance between A and B?**

In [23]:
np.linalg.norm(A - B)

33.46640106136302

# Q1.4
**Find the best rank 2 approximation of A in terms of Frobenius distance.**

In [136]:
###
model = NMF(n_components = 2)

###
W  = model.fit_transform(A)
H  = model.components_
WH = W @ H
print(WH)

[[8.59464669 7.27022485 5.86454921 4.43201883 3.07981859 1.9496519
  1.19922949 0.98478923 1.44696003]
 [7.27020114 6.15670143 4.95475714 3.71463336 2.53199134 1.53188851
  0.85254231 0.6299269  0.98524144]
 [5.86455244 4.95477436 4.00704876 3.05472353 2.16650393 1.43447407
  0.96197843 0.85224171 1.19923266]
 [4.43203848 3.71465263 3.0547352  2.45891924 1.95730392 1.59679577
  1.43447416 1.53168681 1.94965397]
 [3.0798608  2.53201518 2.16653141 1.95731853 1.88921155 1.95730177
  2.1664992  2.53188649 3.07981183]
 [1.94972005 1.53191894 1.43451956 1.59682611 1.95731628 2.45891241
  3.05470928 3.71461191 4.43199608]
 [1.19932454 0.85258108 0.96204239 1.43451967 2.16652633 3.0547204
  4.0070195  4.95479249 5.86450238]
 [0.98491024 0.6299757  0.85232327 1.53174554 2.53192271 3.71462879
  4.95479629 6.1568694  7.2702665 ]
 [1.44710036 0.98529788 1.1993272  1.94972184 3.07985335 4.43201486
  5.86450568 7.2702651  8.59457187]]


**2**. (20 points)

- Find the square root of 123 using the Newton-Raphson method. Write your own Netwon-Raphson function. Use a fixed number of iterations, say 10. Start with an initial guess x0=10.
- Repeat the exercise using Cython
- Time 1000 calls of the python and cython functions using `timeit.timeit`. You should see at least a 10 fold speed up with the Cython version.

# Q2.1
**Find the square root of 123 using the Newton-Raphson method. Write your own Netwon-Raphson function. Use a fixed number of iterations, say 10. Start with an initial guess x0=10.**

In [35]:
def newton_sq(x0 = 10, niter = 10):
    """Newton-Raphson of the square root"""
    x = x0
    for _ in range(niter):
        x -= (x**2 - 123) / (2 * x)
    return x

In [36]:
newton_sq()

11.090536506409418

In [37]:
123**0.5

11.090536506409418

# Q2.2
**Repeat the exercise using Cython**

In [34]:
%%cython -a
def newton_sq_cython(x0 = 10, niter = 10):
    """Newton-Raphson of the square root"""
    cdef float x = x0
    for _ in range(niter):
        x -= (x**2 - 123) / (2 * x)
    return x

In [39]:
np.allclose(newton_sq(), newton_sq_cython())

True

# Q2.3
**Time 1000 calls of the python and cython functions using `timeit.timeit`. You should see at least a 10 fold speed up with the Cython version.**

In [42]:
t1 = timeit.timeit(lambda : newton_sq(),        number = 1000)
t2 = timeit.timeit(lambda : newton_sq_cython(), number = 1000)
print(t1 / t2)

7.387331122420468


**3**. (30 points)

We have 3 documents

Doc 1
```
"Just the place for a Snark!" the Bellman cried,
   As he landed his crew with care;
Supporting each man on the top of the tide
   By a finger entwined in his hair.
```

Doc 2
```
"Just the place for a Snark! I have said it twice:
   That alone should encourage the crew.
Just the place for a Snark! I have said it thrice:
   What I tell you three times is true."
```

Doc 3
```
The crew was complete: it included a Boots—
   A maker of Bonnets and Hoods—
A Barrister, brought to arrange their disputes—
   And a Broker, to value their goods.
```

- Create a count matrix of the unigram and bigram counts using only standard Python libraries and convert to a DataFrame
- Use `sklearn.decomposition.NMF`  with 2 components to find a lower-dimensional feature space
- Calculate the pairwise distance matrix in the reduced feature space using cosine distance. You may use `pdist` and `squareform` from `scipy.spsatial.distance`.

In [47]:
doc1 = '''
Just the place for a Snark!" the Bellman cried,
   As he landed his crew with care;
Supporting each man on the top of the tide
   By a finger entwined in his hair.'''

doc2 = '''
"Just the place for a Snark! I have said it twice:
   That alone should encourage the crew.
Just the place for a Snark! I have said it thrice:
   What I tell you three times is true.'''

doc3 = '''
The crew was complete: it included a Boots—
   A maker of Bonnets and Hoods—
A Barrister, brought to arrange their disputes—
   And a Broker, to value their goods.

'''

# Q3.1
**Create a count matrix of the unigram and bigram counts using only standard Python libraries and convert to a DataFrame**

In [44]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [114]:
def fun_words(string):
    """process input string into bag of words"""
    table = str.maketrans(punctuation, " " * len(punctuation))
    words = string.lower().replace("—", "").replace("-", "").translate(table).split()
    return words

def fun_gram(words):
    """create the bag of unigram and bigram"""
    unigram = words
    bigram  = list(zip(words[:-1], words[1:]))
    return unigram + bigram

def fun_count(words, colname):
    """create dataframe """
    tmp = words
    tmp = fun_words(tmp)
    tmp = fun_gram(tmp)  
    tmp = Counter(tmp)
    df = pd.DataFrame(list(tmp.values()), index = list(tmp.keys()), columns = [colname])
    return df

df1 = fun_count(doc1, "doc1")
df2 = fun_count(doc2, "doc2")
df3 = fun_count(doc3, "doc3")

mycombine = lambda x, y: pd.merge(x, y, how = 'outer', left_index = True, right_index = True, )
df  = reduce(mycombine, [df1, df2, df3])
df  = df.fillna(0)
print(df)

                    doc1  doc2  doc3
with                 1.0   0.0   0.0
(in, his)            1.0   0.0   0.0
care                 1.0   0.0   0.0
place                1.0   2.0   0.0
bellman              1.0   0.0   0.0
his                  2.0   0.0   0.0
finger               1.0   0.0   0.0
top                  1.0   0.0   0.0
(with, care)         1.0   0.0   0.0
(a, finger)          1.0   0.0   0.0
man                  1.0   0.0   0.0
each                 1.0   0.0   0.0
(the, top)           1.0   0.0   0.0
(he, landed)         1.0   0.0   0.0
(snark, the)         1.0   0.0   0.0
of                   1.0   0.0   1.0
(top, of)            1.0   0.0   0.0
(finger, entwined)   1.0   0.0   0.0
(man, on)            1.0   0.0   0.0
(landed, his)        1.0   0.0   0.0
(care, supporting)   1.0   0.0   0.0
(the, bellman)       1.0   0.0   0.0
(the, tide)          1.0   0.0   0.0
(supporting, each)   1.0   0.0   0.0
crew                 1.0   1.0   1.0
(of, the)            1.0   0.0   0.0
t

/opt/conda/lib/python3.5/site-packages/pandas/core/reshape/merge.py:765: RuntimeWarning: unorderable types: str() < tuple(), sort order is undefined for incomparable objects
  sort=self.sort)


# Q3.2
**Use `sklearn.decomposition.NMF`  with 2 components to find a lower-dimensional feature space**

In [128]:
?NMF

In [153]:
###
model = NMF(n_components = 2)

###
W  = model.fit_transform(df)
H  = model.components_
print(H.shape)
print(H)

(2, 3)
[[1.6955385  3.12742258 0.        ]
 [0.36563051 0.         2.75408708]]


# Q3.3
**Calculate the pairwise distance matrix in the reduced feature space using cosine distance. You may use `pdist` and `squareform` from `scipy.spsatial.distance`.**

In [156]:
tmp = pdist(H.T, metric = "cosine")
squareform(tmp)

array([[0.        , 0.02247018, 0.78920282],
       [0.02247018, 0.        , 1.        ],
       [0.78920282, 1.        , 0.        ]])

**4**. (30 points)

Read the time series data in data/ts.csv into a DataFrame where the index consists of the timestamps.

- Detrend the time series by fitting a quadratic regression curve to the original data and subtracting the predicted values from the fitted model
- Plot the detrended time series and superimpose a exponentially weighted mean curve with alpha=0.2
- Plot the ACF for lags up to 30 without using the specialized ACF plots (that is, you need to create a vector of auto-correlations at each lag for the detrended data, then plot that using `matplotlib.pyplot.stem` function)

In [157]:
pd.read_csv("./data/ts.csv")

FileNotFoundError: File b'./data/ts.csv' does not exist