In [4]:
import numpy as np
from scipy.spatial.distance import pdist

In [5]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

M = M.T

In [6]:
M

array([[1, 4],
       [2, 5],
       [3, 6]])

pdist

In [7]:
pdist(M)

array([1.41421356, 2.82842712, 1.41421356])

In [8]:
pdist(M)**2

array([2., 8., 2.])

https://math.stackexchange.com/questions/2240429/pairwise-distance-matrix

In [10]:
G = M @ M.T
g = np.diag(G).reshape(-1, 1)
vone = np.ones(3).reshape(-1, 1)

g @ vone.T + vone @ g.T - 2 * G

array([[0., 2., 8.],
       [2., 0., 2.],
       [8., 2., 0.]])

https://stackoverflow.com/questions/27948363/numpy-broadcast-to-perform-euclidean-distance-vectorized

In [13]:
a = M
b = M
(np.square(a[:, np.newaxis] - b).sum(axis = 2))

array([[0, 2, 8],
       [2, 0, 2],
       [8, 2, 0]])