In [21]:
import numpy as np
import scipy.linalg as la
import itertools as it
from scipy.spatial.distance import pdist

In [5]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

M = M.T

In [6]:
M

array([[1, 4],
       [2, 5],
       [3, 6]])

pdist

In [7]:
pdist(M)

array([1.41421356, 2.82842712, 1.41421356])

In [8]:
pdist(M)**2

array([2., 8., 2.])

https://math.stackexchange.com/questions/2240429/pairwise-distance-matrix

In [10]:
G = M @ M.T
g = np.diag(G).reshape(-1, 1)
vone = np.ones(3).reshape(-1, 1)

g @ vone.T + vone @ g.T - 2 * G

array([[0., 2., 8.],
       [2., 0., 2.],
       [8., 2., 0.]])

https://stackoverflow.com/questions/27948363/numpy-broadcast-to-perform-euclidean-distance-vectorized

In [13]:
a = M
b = M
(np.square(a[:, np.newaxis] - b).sum(axis = 2))

array([[0, 2, 8],
       [2, 0, 2],
       [8, 2, 0]])

In [3]:
M = np.array([[1,2,3],[4,5,6]])
X = M.T

#X = X[:, np.newaxis]
X1 = np.expand_dims(X, axis = 1)
X2 = np.expand_dims(X, axis = 0)

print(X1.shape)
print(X2.shape)

(3, 1, 2)
(1, 3, 2)


In [4]:
D = X1 - X2
np.sum(D**2, axis = 2)

array([[0, 2, 8],
       [2, 0, 2],
       [8, 2, 0]])

In [55]:
k = X1.shape[0]

D = X1 * X2
D = np.sum(D, axis = 2) 
norm = np.diagonal(D).reshape(-1, 1)
vone = np.ones(D.shape[0]).reshape(-1, 1)

print(D / (norm @ vone.T) / (vone @ norm.T))
print("=======")
print(1 - D / (norm @ vone.T) / (vone @ norm.T))

[[0.05882353 0.04462475 0.03529412]
 [0.04462475 0.03448276 0.02758621]
 [0.03529412 0.02758621 0.02222222]]
[[0.94117647 0.95537525 0.96470588]
 [0.95537525 0.96551724 0.97241379]
 [0.96470588 0.97241379 0.97777778]]


this won't work

In [78]:
x = M[:, 0]
y = M[:, 1]

X1 = np.expand_dims(x, axis = 1)
X2 = np.expand_dims(y, axis = 0)

D = np.sum(X1 * X2, axis = 0)
print(D)

[10 25]


this works

In [80]:
M = np.array([[1,2,3],[4,5,6]])
X = M.T

X1 = np.expand_dims(X, axis = 1)
X2 = np.expand_dims(X, axis = 0)

D = np.sum(X1 * X2, axis = 2)
print(D)

[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [83]:
X1 = M[:, 0]
X2 = M[:, 1]

D = X1 * X2
D = np.sum(D, axis = 0)
D.shape

()

In [84]:
np.sqrt(la.norm(X1))

2.0305431848689306

In [87]:
X1 = M[:, 0]
X2 = M[:, 1]

D = X1 * X2
D = np.sum(D, axis = 0)
D = np.array(D)
norm = np.square(la.norm(X1), 
vone = np.ones(D.shape[0]).reshape(-1, 1)

print(D / (norm @ vone.T) / (vone @ norm.T))
print("=======")
print(1 - D / (norm @ vone.T) / (vone @ norm.T))

()

In [95]:
norm

array([[17],
       [29],
       [45]])

In [103]:
print(np.sum(X1 * X1, axis = 2))
print(np.sum(X2 * X2, axis = 2))

[[17]
 [29]
 [45]]
[[17 29 45]]


In [106]:
M = np.array([[1,2,3],[4,5,6]])
X = M.T

X1 = np.expand_dims(X, axis = 1)
X2 = np.expand_dims(X, axis = 0)

D = X1 * X2
D = np.sum(D, axis = 2) 
norm = np.sqrt(np.diagonal(D)).reshape(-1, 1)
vone = np.ones(D.shape[0]).reshape(-1, 1)

print(D)
print("=======")
print(D / (norm @ vone.T) / (vone @ norm.T))

[[17 22 27]
 [22 29 36]
 [27 36 45]]
[[1.         0.99083017 0.97618706]
 [0.99083017 1.         0.99654576]
 [0.97618706 0.99654576 1.        ]]


In [109]:
M = np.array([[1,2,3],[4,5,6]])
X = M.T

X1 = np.expand_dims(X, axis = 1)
X2 = np.expand_dims(X, axis = 0)

D = X1 * X2
D = np.sum(D, axis = 2) 

norm1 = np.sqrt(np.sum(X1 * X1, axis = 2))
norm2 = np.sqrt(np.sum(X2 * X2, axis = 2))

print(D / norm1 / norm2)

[[1.         0.99083017 0.97618706]
 [0.99083017 1.         0.99654576]
 [0.97618706 0.99654576 1.        ]]


In [ ]:
k = X1.shape[0]

D = X1 * X2
D = np.sum(D, axis = 2) 
norm = np.diagonal(D).reshape(-1, 1)
vone = np.ones(D.shape[0]).reshape(-1, 1)

print(D / (norm @ vone.T) / (vone @ norm.T))
print("=======")
print(1 - D / (norm @ vone.T) / (vone @ norm.T))

find the answer for cosine distance

In [46]:
dist_cosine(np.array([1, 2]), np.array([1, 2]))

1.0

In [47]:
pdist(M.T, metric = "cosine")

array([0.00916983, 0.02381294, 0.00345424])

In [111]:
my_pdist_row_loop(M.T, dist_cosine)

array([[0.        , 0.00916983, 0.02381294],
       [0.00916983, 0.        , 0.00345424],
       [0.02381294, 0.00345424, 0.        ]])

In [10]:
import doctest

In [51]:
def dist_euclidean_sq(x, y = None, axis = 0):
    """calculate squared Euclidean distance of numpy vector x and y; if only one vector
    
    >>> x = np.array([3, 4])
    >>> y = np.array([0, 0])
    >>> z = np.array([-2, -8])
    >>> dist_euclidean_sq(x)
    25.0
    >>> dist_euclidean_sq(x, y)
    25.0
    >>> dist_euclidean_sq(y, x)
    25.0
    >>> dist_euclidean_sq(x, z)
    169.0
    """
    ### coerce the type to float
    x = x.copy().astype(np.float)
    
    ### calculate squared euclidean distance
    if y is None:
        # one vector only
        dist = np.sum(np.square(x), axis = axis)     
    else:
        # input two vectors
        dist = np.sum(np.square(x - y), axis = axis) 
        
    return dist

def dist_euclidean(x, y = None, axis = 0):
    """calculate Euclidean distance of numpy vector x and y
    
    >>> x = np.array([3, 4])
    >>> y = np.array([0, 0])
    >>> z = np.array([-2, -8])
    >>> dist_euclidean(x)
    5.0
    >>> dist_euclidean(x, y)
    5.0
    >>> dist_euclidean(y, x)
    5.0
    >>> dist_euclidean(x, z)
    13.0
    """
    dist_sq = dist_euclidean_sq(x, y, axis = axis) #, axis = axis)
    return(dist_sq**0.5)

def dist_cosine(x, y = None, axis = 0):
    """calculate cosince distance of input vectors
    >>> x = np.array([1, 1])
    >>> y = np.array([1, 0]) # x axis
    
    >>> d = dist_cosine(x, y)
    >>> np.allclose(d, 1 - np.cos(np.pi / 4)) # expect: 45 degree
    True
    
    >>> d = dist_cosine(y, x)                 # check d(x, y) = d(y, x)
    >>> np.allclose(d, 1 - np.cos(np.pi / 4)) # expect: 45 degree
    True
    
    >>> x = np.array([1, 3**0.5])
    >>> y = np.array([1, 0]) # x axis
    >>> d = dist_cosine(x, y)
    >>> np.allclose(d, 1 - np.cos(np.pi / 3)) # expect: 60 degree
    True
    
    >>> x = np.array([1, 3**0.5])
    >>> y = np.array([0, 1]) # y axis
    >>> d = dist_cosine(x, y)
    >>> np.allclose(d, 1 - np.cos(np.pi / 6)) # expect: 30 degree
    True
    """
    #scipy.linalg.norm
    #transform the extend array to apply the function on just 
    # axis = 2
    # extends axis
    # y reshape transform
    
    #dist = 1 - np.dot(x, y) / np.dot(x, x)**0.5 / np.dot(y, y)**0.5     
    #dist = 1 - np.dot(x, y) / la.norm(x) / la.norm(y)
    
    D = X1 * X2
    D = np.sum(D, axis = 2) 
    dist = 1 - D / (norm @ vone.T) / (vone @ norm.T)
    
    return dist


### test each function; if passed, no output from the run_docstring_examples
doctest.run_docstring_examples(dist_euclidean_sq, globals())
doctest.run_docstring_examples(dist_euclidean,    globals())
doctest.run_docstring_examples(dist_cosine,       globals())

In [22]:
def my_pdist_row_loop(M, distance_func):
    """calculate the pairwise-distance matrix given the matrix M and some arbitrary distance function
    
    Notes:
    - M is a collection of row vectors
    - using looping instead of broadcasting
    
    >>> M = np.array([[1,2,3],[4,5,6]])
    >>> dist = my_pdist_row_loop(M.T, dist_euclidean) # results
    >>> dist_exp = np.array([                         # expected
    ... [ 0.000,  1.414,  2.828],
    ... [ 1.414,  0.000,  1.414],
    ... [ 2.828,  1.414,  0.000]])
    
    >>> dist_round = np.round(dist, decimals = 3)
    >>> np.allclose(dist_round, dist_exp)
    True
    
    >>> dist = my_pdist_row_loop(M.T, dist_cosine) # results
    >>> dist_exp = np.array([
    ... [0.   , 0.991, 0.976],
    ... [0.991, 0.   , 0.997],
    ... [0.976, 0.997, 0.   ]])
    
    >>> dist_round = np.round(dist, decimals = 3)
    >>> np.allclose(dist_round, dist_exp)
    True
    """
    ### initialization
    nrow, ncol = M.shape
    idx        = np.arange(nrow)
    mat_dist   = np.zeros((nrow, nrow))
    
    ### loop through row pairs
    for idx01, idx02 in it.combinations(idx, 2):
        dist = distance_func(M[idx01], M[idx02])
        mat_dist[idx01, idx02] = dist
        mat_dist[idx02, idx01] = dist
        
    return mat_dist

### test each function; if passed, no output from the run_docstring_examples
doctest.run_docstring_examples(my_pdist_row_loop, globals())